begin;

-- Public content can be read anonymously. All writes go through authenticated
-- Next.js API routes using the backend-only service role.
alter table public.posts enable row level security;
alter table public.comments enable row level security;

do $$
declare policy_record record;
begin
  for policy_record in
    select policyname, tablename
    from pg_policies
    where schemaname = 'public' and tablename in ('posts', 'comments')
  loop
    execute format('drop policy if exists %I on public.%I', policy_record.policyname, policy_record.tablename);
  end loop;
end $$;

revoke insert, update, delete, truncate, references, trigger on public.posts from anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on public.comments from anon, authenticated;
grant select on public.posts to anon, authenticated;
grant select on public.comments to anon, authenticated;

create policy "Public can read posts"
  on public.posts for select
  to anon, authenticated
  using (true);

create policy "Public can read comments"
  on public.comments for select
  to anon, authenticated
  using (true);

-- Backend-only persistent rate limits. RLS intentionally has no client policies.
create table if not exists public.api_rate_limits (
  key text not null,
  window_start timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  primary key (key, window_start)
);
alter table public.api_rate_limits enable row level security;
revoke all on public.api_rate_limits from anon, authenticated;

create or replace function public.consume_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_window timestamptz;
  current_count integer;
begin
  if length(p_key) > 300 or p_limit < 1 or p_window_seconds < 1 then
    raise exception 'Invalid rate-limit parameters';
  end if;

  current_window := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  insert into public.api_rate_limits (key, window_start, request_count)
  values (p_key, current_window, 1)
  on conflict (key, window_start)
  do update set request_count = public.api_rate_limits.request_count + 1
  returning request_count into current_count;

  delete from public.api_rate_limits
  where window_start < clock_timestamp() - interval '2 days';

  return current_count <= p_limit;
end;
$$;

revoke all on function public.consume_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;

-- Login auditing supports server-enforced lockout. Only the service role can access it.
create table if not exists public.admin_login_attempts (
  id bigint generated by default as identity primary key,
  identifier text not null,
  success boolean not null,
  ip_hash text not null,
  user_agent text not null,
  created_at timestamptz not null default now()
);
create index if not exists admin_login_attempts_lookup_idx
  on public.admin_login_attempts (identifier, success, created_at desc);
alter table public.admin_login_attempts enable row level security;
revoke all on public.admin_login_attempts from anon, authenticated;

-- Atomic public like mutation, callable only by the backend service role.
create or replace function public.increment_post_likes(p_post_id text)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare updated_likes integer;
begin
  update public.posts
  set likes = coalesce(likes, 0) + 1
  where id::text = p_post_id
  returning likes into updated_likes;
  return updated_likes;
end;
$$;

revoke all on function public.increment_post_likes(text) from public, anon, authenticated;
grant execute on function public.increment_post_likes(text) to service_role;

-- Delete a post and its comments in one transaction. A public media URL is converted
-- to its storage object path so the API can remove the object after the DB commit.
create or replace function public.delete_post_and_comments(p_post_id text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_slug text;
  target_media_url text;
  storage_path text;
begin
  select slug, image_url into target_slug, target_media_url
  from public.posts
  where id::text = p_post_id
  for update;

  if target_slug is null then
    return jsonb_build_object('deleted', false);
  end if;

  delete from public.comments where post_slug = target_slug;
  delete from public.posts where id::text = p_post_id;

  if target_media_url like '%/storage/v1/object/public/media/%' then
    storage_path := split_part(target_media_url, '/storage/v1/object/public/media/', 2);
  end if;

  return jsonb_build_object('deleted', true, 'storage_path', storage_path);
end;
$$;

revoke all on function public.delete_post_and_comments(text) from public, anon, authenticated;
grant execute on function public.delete_post_and_comments(text) to service_role;

-- This project owns the media bucket. Remove legacy Storage policies so a permissive
-- policy cannot bypass the server API, then allow public reads only.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media',
  'media',
  true,
  26214400,
  array['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime', 'video/webm']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
declare policy_record record;
begin
  for policy_record in
    select policyname
    from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
  loop
    execute format('drop policy if exists %I on storage.objects', policy_record.policyname);
  end loop;
end $$;

create policy "Public can read media"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'media');

commit;
